### ISSUE TITLE
User editing a locality cannot create a conflicting min/max age

### ISSUE THREAD

**Issue by iritmaximus** [nowcommunity/nowdatabase#141]
**Min** age cannot be greater than **max** age and vice versa **max** age cannot be smaller than **min** age

- [x] Frontend checks for incorrect ages and displays an error message
- [x] Backend checks for incorrect ages and returns an error code
- [x] Tests

**Comment by karilint** [comment]
If you select Basis for Age (time unit) for Locality, e.g. mn15 for both, the minimum and maximum age values should ​​become 3.55 and 5. That is, the Minimum value is always the Upper limit value in the selection list and the Maximum value is always the Lower limit value (in addition, the possible fractional part of the age has to be taken into account). I'll accept this issue because the minimum cannot exceed the maximum, but this functionality is not working completely yet.
