### ISSUE TITLE
User can filter years in reference table view with minimum and maximum year range

### ISSUE THREAD

**Issue by iritmaximus** [nowcommunity/nowdatabase#145]

**Comment by EeroAnt** [comment]
#312

**Comment by karilint** [comment]
If you set the minimum to 2003 and the maximum to 2005, only the results for 2004 are displayed. Those should be from 2003 to 2005.

**Comment by iritmaximus** [comment]
This is "intended" behaviour by Material. Here is a [demo](https://www.material-react-table.com/docs/guides/column-filtering#customize-filter-modes-demo) that has the same behaviour.

**Comment by iritmaximus** [comment]
Fixed in #474.

**Comment by karilint** [comment]
**Test results:**

Currently, it seems that nothing works with the year filtering

**Comment by juhanikat** [comment]
This is now tracked in #527

**Comment by karilint** [comment]
Tested - OK.

Other comments:
Enter search term: valid entries: (in PHP version) 
2004, <2004, >2004, 
2004. .2005 (min: 1700, 
max: 2024, missing year: O)

**Comment by juhanikat** [comment]
Are you referring to the features that are talked about in #132 ?
If so, the fuzzy/exact search feature is tracked in #377 
And because we have a different input field for the minimum and maximum year in the table, these search terms are already implemented in a different way: `2004, <2004, >2004, 2004...2005`
I am not sure what `(min: 1700, max: 2024, missing year: O)` means, could you clarify?

**Comment by karilint** [comment]
Test results: **Approved**

You are right. Those PHP search terms are now implemented.
