### ISSUE TITLE
User can clearly see that saving an impossible locality edit is not possible

### ISSUE THREAD

**Issue by juhanikat** [nowcommunity/nowdatabase#171]
At the moment you can click save and finalize and think that you have saved something, when in fact nothing has been saved. Maybe gray out the save button while editing if there are incorrect values in any fields?

**Comment by juhanikat** [comment]
Related to #190

**Comment by karilint** [comment]
Currently, when you create a new Locality (with empty values), the "Finalize entry" button is enabled. It is only when you press "Complete and save" that the error message "Could not save item. Missing: Locality name, Age (max), Age (min), Latitude (dms), Longitude (dms), Latitude (dec), Longitude (dec), Country," comes. 

Could this be improved so that the "Finalize entry" button is disabled until the required fields are filled in and there are no errors? Or, when the button is pressed it shows the error messages and does not proceed until all is fixed?
