### ISSUE TITLE
User is told why creating a new entry fails

### ISSUE THREAD

**Issue by juhanikat** [nowcommunity/nowdatabase#209]
At the moment you can, for example, create a new locality, not fill in any fields, and click finalize/complete entry. Maybe after clicking finalize, do not navigate to the staging view and instead show in red any fields that cannot be empty?

**Comment by juhanikat** [comment]
Related to #190

**Comment by karilint** [comment]
Currently, when you create a new Locality (with empty values), the "Finalize entry" button is enabled. It is only when you press "Complete and save" that the error message "Could not save item. Missing: Locality name, Age (max), Age (min), Latitude (dms), Longitude (dms), Latitude (dec), Longitude (dec), Country," comes.

Could this be improved so that the "Finalize entry" button is disabled until the required fields are filled in and there are no errors? Or, when the button is pressed it shows the error messages and does not proceed until all is fixed?

New Locality
- Country could be a dropdown field
- If the filled-in values are wrong, the UI clears all previously entered data

New Species
- Maybe another story: Start from a blank or copy higher taxonomy from an existing species?
- If one fills in all but one required field, the error is displayed for the one field but the others are blank again.
