### ISSUE TITLE
User can edit existing time units without a reference

### ISSUE THREAD

**Issue by juhanikat** [nowcommunity/nowdatabase#216]
~~There is a bug that prevents editing the time unit name, more info in #173~~
ignored, see comment

**Comment by iritmaximus** [comment]
- [ ] User without editing rights cannot edit time units
- [ ] User with editing rights can edit time units with valid inputs
- [ ] User with editing rights and *incorrect* input cannot edit time units and is notified about it
- [ ] User with editing rights and *incorrect* input is notified about it
- [ ] After succesfully editing, logs are updated correctly
- [ ] Tests are implemented
- [ ] Documentation is written

**Comment by juhanikat** [comment]
Started in sprint 2, continued in sprint 3

**Comment by juhanikat** [comment]
- [ ] #327 
- [ ] #301 
- [ ] #298 
- [ ] #326 
- [ ] #322

**Comment by kaarleol** [comment]
Continued in sprint 4

**Comment by juhanikat** [comment]
The issue preventing the user from changing time unit name is too complex and involves changing the structure of the database, so we will ignore it for this user story

**Comment by karilint** [comment]
The user can still edit (or even add?) Time Unit without a Reference. The name of the task is misleading. It should be "User **can't** edit existing time units without a reference.

**Comment by karilint** [comment]
Test results:
- [x] OK: User without editing rights cannot edit time units
- [x] OK: User with editing rights can edit time units with valid inputs
- [x] OK: User with editing rights and *incorrect* input cannot edit time units and is notified about it
- [x] OK: User with editing rights and *incorrect* input is notified about it
- [x] OK: After successfully editing, logs are updated correctly
- [x] Possibly OK: Tests are implemented
- [x] OK: Documentation is written
- [x] OK: Localities don't break

Time Unit (other notes):
- The heading should be something like: "(abdounian) Abdounian - African Land Mammal Ages 55 Ma – 56 Ma AFLMA Age", see PHP
- In edit mode, the returned value from Sequence should show the "Display value" of the selection, not the "Hidden Value", see. "Central Paratethys" instead of "centralparatethys"
- Name, Rank, Sequence, Comment should be the order of the fields on "Time Unit" section
- Instead of displaying "New Upper Bound Id" and "New Lower Bound Id" in the "Edit bounds" section, all other fields should be shown too
- Lower bound and Upper bound sections should be in a different order: Upper above Lower
- for some reason, the logs of a Time Unit changes are displayed on the new interface but not on the PHP
	See abdounian
- When editing a Time Unit that could break a Locality's min/max ages, the warning message is displayed anly for some time and then fades away. It could stay until the user responds to something.

**Comment by juhanikat** [comment]
Thank you, I added an issue #578 to track these suggestions 👍
