### ISSUE TITLE
User can create a locality without a reference

### ISSUE THREAD

**Issue by iritmaximus** [nowcommunity/nowdatabase#231]

**Comment by iritmaximus** [comment]
- [ ] User without writing rights cannot create a locality
- [ ] User with writing rights can create a locality with valid inputs
- [ ] User with writing rights and *incorrect* input cannot create a locality and is notified about it
- [ ] User with writing rights and *incorrect* input is notified about it
- [ ] Age can be selected using time units (and fractions)
- [ ] Coordinates are converted from dms to angles and the other way around
- [ ] User must select basis for age when selecting absolute time mode
- [ ] Changing time mode resets other time related fields
- [ ] User cannot change absolute when time unit is selected
- [ ] Tests are implemented
- [ ] Documentation is written

**Comment by realtalin** [comment]
- [ ] #256
- [ ] #257
- [ ] #258
- [ ] #259
- [ ] #260
- [ ] #261
- [ ] #262

**Comment by juhanikat** [comment]
Started in sprint 2, continued in sprint 3

**Comment by karilint** [comment]
**Test results:**

- [] Partly OK: User without writing rights cannot create a locality
	 If normal www-user tries a link for a new Locality, the page is displayed although nothing is saved: https://nowdb-frontend-nowdatabase.ext.ocp-test-0.k8s.it.helsinki.fi/locality/new?tab=0
- [] Not OK. User with writing rights can create a locality with valid inputs
	At leasts, the "Dating method" should have a value (see below)
- [] Not OK. User with writing rights and *incorrect* input cannot create a locality and is notified about it
	Current validators: Locality name, Age (max), Age (min), Latitude (dms), Longitude (dms), Latitude (dec), Longitude (dec), Country
	Additional PHP validators: Basis for age (Absolute) or (Time Unit) are required (now one can set Age Ma without any of the Basis)
	One can add a number to the Age (Ma) and it can be saved without any value in Absolute or Time Unit
- [x] OK: User with writing rights and *incorrect* input is notified about it
- [x] OK: Age can be selected using time units (and fractions)
- [x] OK: Coordinates are converted from dms to angles and the other way around
- [x] OK: User must select basis for age when selecting absolute time mode
- [x] OK: Changing time mode resets other time related fields
- [x] OK: User cannot change absolute when time unit is selected
- [x] Possibly OK: Tests are implemented
- [x] Documentation is written

Locality:
- Locality heading could be something like: 21390 Aarau, Switzerland 47 23 0 N, 8 3 0 E14.2 Ma (MN 6) – 12.85 Ma (MN 6)
- the tabs that contain required fields could be highlighted
- if error happens the already entered values are cleared
- Country should be a dropdown field
- On Map selector, the pin image is missing
- Instead of "Open Map" use "Get Coordinates"
- The "Dating method" should be selected before one can enter anything to Min & Max ages
	- see how selecting the absolute-composite-time unit changes the UI on PHP
	- Selecting Basis for age (Time Unit) first and then Basis for age (Fraction) should then change the Age (Ma). Now one needs to select them in different order which is not intuitive

- Does a deletion of a Locality still create Log entries?

**Comment by realtalin** [comment]
Thank you for the feedback

For the critical issues:

First item is now being tracked at #511

Second and third item should be partly resolved by #497. The dating method radio selector should have a default value, and a state of no seleceted value should not be reachable, but a validator requiring it can be added regardless. Logic for the required fields when the dating method is composite isn't implemented however. It's now being tracked in #512

Task for documentation at #513

**Comment by realtalin** [comment]
Critical issues fixed, moved to done

**Comment by karilint** [comment]
I'll check the other issues later.

**Comment by realtalin** [comment]
Sorry for the confusion, but I had forgotten to add the issue about fractions not working at all to this story, definitely needs to be fixed before this can be called done. Reopening for now.

**Comment by karilint** [comment]
Test results: **Approved**
- still the "Basis for age (Fraction)" needs to be selected before the Time Unit
- if "Time Unit" is selected first and "Basis for age (Fraction)" after, the UI calculates the values wrongly but also saves the wrong values

**Comment by realtalin** [comment]
First item tracked in #450
Created issue to track age validation at #575
Great catch on the last item, as it seems to be a larger bug. If edit any Locality/Species/Time Unit/Time Bound, and try to clear a previously filled field in that edit, it won't work. The editData correctly gets cleared, but the new null value does not get writted to the database. Tracked in #576
