### ISSUE TITLE
User doesn't have to wait a minute for CrossSearch to load

### ISSUE THREAD

**Issue by iritmaximus** [nowcommunity/nowdatabase#376]

**Comment by juhanikat** [comment]
- [ ] Cross-search load time is improved when opening it
- [ ] Cross-search load time is benchmarked
- [ ] Tests are implemented
- [ ] Documentation is written

**Comment by iritmaximus** [comment]
Implementing the wanted sql query is not supported in prisma. Implementing it as raw sql would require taking user input as unsanitized strings which is for sure not wanted behaviour.

**Comment by karilint** [comment]
Tested: **Not approved**
- still very slow (45 s in Staging)
- on MariaDB the query and output takes about 10 s.

SELECT *
FROM now_ls ls
(LEFT) JOIN now_loc l ON l.lid=ls.lid
(LEFT) JOIN com_species s ON s.species_id=ls.species_id

INNER JOIN on Staging: Duration for 1 query: 0.015 sec. (+ 9.750 sec. network) /
Duration for 1 query: 0.000 sec. (+ 9.953 sec. network)/
On production: Duration for 1 query: 0.016 sec. (+ 10.109 sec. network) *

LEFT OUTER JOIN on Staging: Duration for 1 query: 0.000 sec. (+ 16.437 sec. network) /
Duration for 1 query: 0.016 sec. (+ 10.062 sec. network)/
O: Duration for 1 query: 0.016 sec. (+ 4.968 sec. network) */n Production

- I noticed that after the first time of loading the CrossSearch when I change lists and come back later to CrossSearch, the list is fast
- could it be so that the list in in memory for some time?
- can it be used for our purpose so that when user comes to the site, it coud pre-load the CrossSearch into memory?

**Comment by iritmaximus** [comment]
Nevermind, if you just change the dabatase query from prisma to raw SQL the query now executes in 10s compared to the earlier 40s.

**Comment by EeroAnt** [comment]
started in sprint 5

**Comment by EeroAnt** [comment]
Final addition to docs in #592. We thought that for now we would not build stress tests for this query. It seems to outperform prismas findmany by a big margin. Testing would require to keep the alternative query up as well as expanding the test database enough that some performance could be reasonably measured (atm test db's cross search is 20 rows.) Please let us know if you'd like something made different

**Comment by ShootingStar91** [comment]
> Final addition to docs in #592. We thought that for now we would not build stress tests for this query. It seems to outperform prismas findmany by a big margin. Testing would require to keep the alternative query up as well as expanding the test database enough that some performance could be reasonably measured (atm test db's cross search is 20 rows.) Please let us know if you'd like something made different

Prisma doesn't do joins in db, it actually just fetches everything and joins it in the apps memory (which is horrible, sorry for picking prisma, honeslty). The limited resources of the server pod means you'll likely see a far greater improvement in staging/production performance than on your own PC

**Comment by karilint** [comment]
Tested - **OK**

Now it takes around 15-20 s to populate the list. Is there a possibility to add some info about the long loading time?
