### ISSUE TITLE
Deleting a species sometimes throws an internal server error

### ISSUE THREAD

**Issue by juhanikat** [nowcommunity/nowdatabase#405]
Deleting a species sometimes throws an internal server error:
```
nowdb-backend-dev   | 10.30.21 Cannot read properties of undefined (reading 'updates')
nowdb-backend-dev   | 10.30.21 TypeError: Cannot read properties of undefined (reading 'updates')
nowdb-backend-dev   |     at deleteSpecies (/usr/src/app/backend/src/services/write/species.ts:52:22)
nowdb-backend-dev   |     at <anonymous> (/usr/src/app/backend/src/routes/species.ts:39:3)
```
This happened to me when trying to delete the "Mustela lutreola" species, for example.

**Comment by iritmaximus** [comment]
This error occurs because there is this random line https://github.com/nowcommunity/nowdatabase/blob/3db206b5c9c8959a8089e091622dc4f244992d2e/backend/src/services/write/species.ts#L52
which appears to do nothing. Removing this fixes the crashes, but I want to make sure nothing breaks by deleting it so I'll write few tests to check nothing bad happens.

**Comment by ShootingStar91** [comment]
> @ShootingStar91 do you have an input on this line? Is the meaning to throw an error if `now_sau` is empty?

No idea, must be a remnant of some debugging or whatever. Probably fine to just delete the line
