### ISSUE TITLE
add proper id's for all editingComponents

### ISSUE THREAD

**Issue by juhanikat** [nowcommunity/nowdatabase#516]
At least FieldWithTableSelections still use weird id's that make testing them much harder.

**Comment by realtalin** [comment]
Added id's for the table selection components in #524 

Only component type that doesn't have an explicit id is now the radioSelection, but that isn't critical since it has properties like `aria-labelledby` and `name` that can be used to single it out in tests. For example, options of the dating method radio selector are singled out in tests with `'[name=dating-method][value=absolute]'`
